### ISSUE TITLE
Alternative encoding for nodes in Egographs

### ISSUE THREAD

**Issue by ThHarbig** [UniTuebingen-BDVA/ProtEGOnist#106]
When there is a lot of nodes in an egograph the circles overlap. Possible solutions
- Replace circle by arc portion if a set minimal circle radius is reached (Issue: Different encodings for same thing)
- Always replace the circle by arc portion (Issue: Looks like donut chart, not necessarily intuitive that arc portions=node)
- Replace circle by arc portion but set a maximal arc portion width

**Comment by NiBrc** [comment]
implemented in  https://github.com/UniTuebingen-BDVA/ProtEGOnist/tree/NiBrc/scaleCircle
