### ISSUE TITLE
Improve animated transitions when decollapsing nodes

### ISSUE THREAD

**Issue by ThHarbig** [UniTuebingen-BDVA/ProtEGOnist#116]
The transitions when decollapsing nodes are quite hard. A lot of things move and the bundle just "appears". To improve this the bundles could be drawn first with the original node positions and then moved to their final location

**Comment by ThHarbig** [comment]
Idea: stepwise transition
Case 1: click on edge and decollapse 2 nodes at the same time
1. Decollapse individual nodes in their original position with the final node layout but do not yet draw identity edges. The shared nodes should be rotated towards each other.
2. Move to their final positions, but place them on a line parallel to the one they were originally placed at
3. draw the identity edges/bands between the ego graphs

Case 2: click on edge to add a third node to a bundle
1. Decollapse individual node in its original position with the final node layout but do not yet draw identity edges. The shared nodes should be rotated towards the imaginary line going through the already existing bundle.
2. Move ego graphs to their final positions. Move the first to graphs on a line parallel to the previous line and keep the new ego graph on the same side of the line.
3. 3. draw the identity edges/bands between the new ego graph and the other ego graphs in the bundle

**Comment by mwittep** [comment]
@ThHarbig Not sure if it fits here, but nodes without a ego-neighborhood can be collapsed and kind of bug the viz.
